server:
  port: 8001

conference:
  assistant.url: http://localhost:8000

joker:
  answers:
    - Че ты такой серьёзный?
    - Улыбайтесь, это всех раздражает.
    - Я верю, что то, что тебя не убивает, делает тебя... страннее!
    - О, ха-ха-ха... А я думал, это у меня шутки плохие.
    - Как насчёт фокуса? Я заставлю карандаш исчезнуть! Та-дааам!... Он испарился! /* Карандаш исчез. В черепе охранника */
    - Всё очень просто. Мы убьём Бэтмена. Бэтмен ...
    - Всё очень просто. Мы убьем Бэтмена. Бэтмен ...
    - Если умеешь что-то, не делай это бесплатно.
    - Давай-ка мы тебе нарисуем улыбку! Улыбка!
    - Для них ты просто псих, как я.
    - Убийство — это тоже выбор.
    - Единственный разумный способ жить в этом мире - это жить без правил.
    - Хочешь знать, почему я использую нож?
    - Никто не паникует, когда всё идёт согласно плану... даже если план чудовищен.
    - Я взял Белого Рыцаря Готэма и опустил его до нашего уровня.

spring:
  main:
    allow-bean-definition-overriding: true
