server:
  port: 8000
logging.level.org.springframework.web: DEBUG

conference:
  joker.url: http://localhost:8001
  jbaruch.url: http://localhost:8002

tokens:
  jbaruch: npm leftpad artifactory артифактори groovy груви nexus нексус телефон binary repository manager бинарный репозиторий зависимостей барух jbaruch бинтрей bintray дистрибуция дистрибуции ***ки технологии технология колодцы рушь мочи tshaped t-shaped вуайеризм омск омске омский мясокомбинат
  joker: joker карандаш серьёзный серьезный джокер бэтман улыбка улыбку улыбаться smile confuse убивает убить ха-ха-ха ха хаха ха-ха фокус фокуса просто бэтмен убьем убьём бесплатно псих выбор правила правил способ разумный нож знать хочешь план плану никто паникует паника опустил готэма готэм рыцарь рыцаря использую шутки шутка убивать

assistant.default:
  answers:
    - ты шутишь? Даже дети знают ответ на этот вопрос!
    - ты бы еще про семантику volatile спросил!
    - это не этичный вопрос

logging.level:
  org.springframework.test.context.cache: debug
  org.hibernate: error
#debug: true

spring:
  groovy:
    template:
      cache: false
  main:
    allow-bean-definition-overriding: true
